server:
  port: 9191

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: TEAM-SERVICE
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/api/team-service/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/**
        - id: MAIL-SERVICE
          uri: lb://MAIL-SERVICE
          predicates:
            - Path=/api/mail-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedHeaders:
              - Content-Type
              - Cache-Control
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowCredentials: true