eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name : MAIL-SERVICE
  mail:
    username: ssm2023.noreply
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
        debug: 'true'
    default-encoding: UTF-8
    host: smtp.gmail.com
    test-connection: 'false'
#    password: ybwxayuw--euqvswcn
    password: xhnnoqluhdliqhej
  thymeleaf:
    cache: 'false'
    suffix: .html

server:
  port: '3008'



